Gestures: Launch via the correct fragment class
java.lang.IllegalArgumentException: Invalid fragment for this activity:
com.android.settings.gestures.GestureSettings

This class has been moved to our main directory.
- Also make sure the "Device" category is third from last

Change-Id: Ie5b70a3cfd0780dd81f83076d51e9ec42ed11608