Additions: Fix button settings crash
java.lang.RuntimeException: Unable to start activity ComponentInfo
{com.android.settings/com.android.settings.SubSettings}: android.view.InflateException:
Binary XML file line #29: Error inflating class (not found)com.android.settings.aoscp.preference.ButtonBacklightBrightness

RTE due to a bad path

- Also update smartpulldown summary logic

Change-Id: Ib107c2bd32b154a4bdea54f9ad3b770d0203417c